#
# Module manifest for module 'helpers'
#
# Generated by: Andrius Solopovas
#
# Generated on: 24/Sep/22
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'helpers.psm1'

    # Version number of this module.
    ModuleVersion     = '2.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = '284e0069-a6c6-4c8c-a8a1-3fa6b6ea46db'

    # Author of this module
    Author            = 'Andrius Solopovas'

    # Company or vendor of this module
    CompanyName       = 'Lyntouch Ltd'

    # Copyright statement for this module
    Copyright         = '(c) Andrius Solopovas. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'A collection of powershell utilities to help with daily tasks.'

    # Minimum version of the PowerShell engine required by this module
    # PowerShellVersion = ''

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    # FunctionsToExport surounded by single quotes
    FunctionsToExport = @(
        'Test-Helpers'
        'Build-WebConfig',
        'Clear-EnvPath',
        'Enable-Feature',
        'Find-LockingProcess',
        'Get-RootName',
        'IIf',
        'New-Passowrd',
        'New-ShellContextItem',
        'Remove-Alias',
        'Repair-Windows',
        'Restart-Explorer',
        'Start-AsAdmin',
        'Sync-Config',
        'Test-EnvPath',
        'Test-ScheduledTask',
        'Test-RegistryValue',
        'Test-RegistryKeyExist',
        'tail',
        # add.ps1
        'Add-ToPath',
        'Add-AdminShortcut',
        'Add-StartupItem',
        'Add-ShellContext',
        'Add-SSHKey',
        # convertions.ps1
        'Convert-ToUnixEndings',
        'Convert-ExcelToCsv',
        'Convert-ExcelToCsvDir',
        'Format-String',
        # files.ps1
        'New-SymLink',
        'New-HardLink',
        'New-File',
        'NerdFontInstall',
        'Test-IsSymLink',
        'Find-Replace',
        'Get-File',
        # rm-patter.ps1
        'Remove-ByPattern',
        # security.ps1
        'FBlocker',
        'Set-FirewallRule',
        'Add-DefenderExclusion',
        'Add-ProjectToPath'
        'Clear-DefenderHistory',
        'Set-AntivirusMode',
        # sync-config.ps1
        'Sync-Configs',
        # wsl-helpers.ps1
        'PortProxy',
        'DistroImport',
        'DistroRemove',
        'gitRmPreviousCommits',
        'sshCopyID',
        'RefreshUserPath'
    )

}
