[Rainmeter]
@include=#SKINSPATH#Personal\Variables\Fonts.inc
Author=lilshizzy@gmail.com

[Metadata]
Name=SM DateTime Simple Saver
Config=
Description=A simple & efficient way to keep time, with style.
Instructions='Click & drag' to your preferred position. If you're comfortable editing simple color code customize to your liking.
Version=
Tags=Thanks to bobbyperux.deviantart.com and his SIMPLE CLOCK SAVER for inspiring this.
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0
Variant=
Preview=lilshizzy.deviantart.com

[MeasureTime]
Measure=Time
Format="%H:%M:%S"

[MeasureTime2]
Measure=Time
Format="%p"

[MeasureYear]
Measure=Time
Format="%Y"

[MeasureDate]
Measure=Time
Format=%d

[MeasureMonth]
Measure=Time
Format=%B
Substitute="January":"JANUARY","February":"FEBRUARY","March":"MARCH","April":"APRIL","May":"MAY.","June":"JUNE","July":"JULY","August":"AUGUST","September":"SEPTEMBER","October":"OCTOBER","November":"NOVEMBER","December":"DECEMBER"

[MeasureDay1]
Measure=Time
Format=%A
Substitute="Monday":"MONDAY","Tuesday":"TUESDAY","Wednesday":"WEDNESDAY","Thursday":"THURSDAY","Friday":"FRIDAY","Saturday":"SATURDAY","Sunday":"SUNDAY"

[Variables]
@include=#SKINSPATH#Personal\Variables\Default.inc


-------------------------------------METERS--------------------------------------------
[Background]
Meter=IMAGE
SolidColor=0,0,0,1
X=0
Y=0
W=600
H=100

[MeterYear]
MeasureName=MeasureYear
Meter=STRING
W=600
X=600
Y=0
FontColor=#Color1#
FontSize=40
FontFace=#LocalFontFace3#
StringAlign=Right
StringStyle=Bold
AntiAlias=1

[MeterMonth]
MeasureName=MeasureMonth
Meter=STRING
W=200
X=212r
Y=0r
FontColor=#Color1#
FontSize=40
FontFace=#LocalFontFace3#
StringAlign=Right
StringStyle=Bold
AntiAlias=1

[MeterDate]
MeasureName=MeasureDate
Meter=STRING
X=75r
Y=r
FontColor=#Color3#
FontSize=40
FontFace=#LocalFontFace3#
StringAlign=Right
StringStyle=Bold
AntiAlias=1


[MeterDay1]
MeasureName=MeasureDay1
Meter=STRING
X=0r
Y=50r
FontColor=#Color3#
FontSize=40
FontFace=#LocalFontFace3#
StringAlign=Right
StringStyle=Bold
AntiAlias=1

[MeterTime]
MeasureName=MeasureTime
Meter=STRING
W=120
X=r
Y=50r
FontColor=#Color1#
FontSize=40
FontFace=#LocalFontFace4#
StringAlign=Right
StringStyle=Normal
AntiAlias=1

; [MeterTime2]
; MeasureName=MeasureTime2
; Meter=STRING
; W=200
; X=r
; Y=80r
; FontColor=#Color3#
; FontSize=40
; FontFace=#LocalFontFace3#
; StringAlign=Right
; StringStyle=Bold
; AntiAlias=1
