[Rainmeter]
;;Backgroung settings
Update=1000
AccurateText=1

[Metadata]
Name=Flair Time
Author=imonline.deviant.com
Information=Based on system_flair_conky__by_speedracker.devianart.com (Linux)
Version=August 10, 2018
License=Creative Commons Attribution-Non-Commercial-Share Alike 3.0

[Variables]
@Include=#@#Variables.inc

;Date and Time-----------------------------

[MeasureTime]
Measure=Time
Format=%H:%M:%S

[MeasureDay]
Measure=Time
Format=%A, %d %B

;[MeterToday]
;Meter=String
;X=275
;Y=0
;StringAlign=right
;FontFace=#FontName#
;FontColor=#FontColor#
;FontSize=25
;AntiAlias=1
;Text="Today"

[MeterTime]
MeasureName=MeasureTime
Meter=STRING
X=275
Y=30R
FontColor=#FontColor#
FontSize=55
FontFace=#FontName#
StringAlign=right
AntiAlias=1

[MeterDay1]
Meter=STRING
MeasureName=MeasureDay
X=275
Y=5R
StringAlign=right
FontColor=#FontColor#
FontSize=17
FontFace=#FontName#
AntiAlias=1

;Separation--------------------------------

[MeterLine]
Meter=Image
ImageName=#@#images\line.png
X=300
Y=20
;H=500

;System Info-------------------------------

;[MeterSystem]
;Meter=String
;X=315
;Y=0
;StringAlign=left
;FontFace=#FontName#
;FontColor=#FontColor#
;FontSize=25
;AntiAlias=1
;Text="System"

[MeasureCore1Temp]
Measure=Plugin
Plugin=CoreTemp
CoreTempType=Temperature
CoreTempIndex=0

[TempIcon]
Meter=Image
ImageName=#@#images\therm.png
X=310
Y=-140R
H=24
W=24

[MeterCore1Temp]
Meter=String
MeasureName=MeasureCore1Temp
X=342
Y=r
StringAlign=left
FontColor=#FontColor#
FontSize=16
FontFace=#FontName#
AntiAlias=1
Text="%1#u-Degree#C"

[MeasureCPUAvg]
Measure=CPU
Processor=0

[CPUIcon]
Meter=Image
ImageName=#@#images\chip.png
X=310
Y=5R
H=24
W=24

[MeterCPU%]
MeasureName=MeasureCPUAvg
Meter=String
X=342
Y=r
StringAlign=left
NumOfDecimals=0
Percentual=1
StringAlign=left
FontColor=#FontColor#
FontSize=16
FontFace=#FontName#
AntiAlias=1
Text="%1% / 100%"

[MeasurePhysMemTotal]
Measure=PhysicalMemory
Total=1
UpdateDivider=3600

[MeasurePhysMemUsed]
Measure=PhysicalMemory
UpdateDivider=2

[RamIcon]
Meter=Image
ImageName=#@#images\micro.png
X=310
Y=5R
H=24
W=24

[MeterMem]
MeasureName=MeasurePhysMemUsed
MeasureName2=MeasurePhysMemTotal
Meter=String
X=342
Y=r
StringAlign=left
;Percentual=1
FontColor=#FontColor#
FontSize=16
FontFace=#FontName#
NumOfDecimals=1
AutoScale=1
AntiAlias=1
Text="%1B / %2B"

;[MeasureNetIn]
;Measure=NetIn
;Interface=#Interface#
;MinValue=0
;MaxValue=(#MaxDownloadMb# * 1048576)

;[NetInIcon]
;Meter=Image
;ImageName=#@#images\dwn.png
;X=310
;Y=5R
;H=24
;W=24

;[MeterNetInText]
;MeasureName=MeasureNetIn
;Meter=String
;X=342
;Y=r
;StringAlign=left
;AutoScale=1
;NumOfDecimals=1
;FontColor=#FontColor#
;FontSize=16
;FontFace=#FontName#
;AntiAlias=1
;DynamicVariables=1
;Text=%1B

;[MeasureNetOut]
;Measure=NetOut
;Interface=#Interface#
;MinValue=0
;MaxValue=(#MaxUploadMb# * 1048576)

;[NetOutIcon]
;Meter=Image
;ImageName=#@#images\up.png
;X=310
;Y=5R
;H=24
;W=24

;[MeterNetOutText]
;MeasureName=MeasureNetOut
;Meter=String
;X=342
;Y=r
;StringAlign=left
;AutoScale=1
;NumOfDecimals=1
;FontColor=#FontColor#
;FontSize=16
;FontFace=#FontName#
;AntiAlias=1
;DynamicVariables=1
Text=%1B


