[gui]
# Should the LaunchBox be always on top of other windows when displayed?
# * Type: Boolean
# * Default: no
always_on_top = yes
theme = AnthraciteFull,PurpleNightColors
hide_on_focus_lost = immediate

[app]
launch_at_startup = yes
hotkey_run = win+d