$php_location = "C:\tools\php74"
$dev_root = "C:\code"
$cache = "C:\code\.cache"
$dev_configs = "$env:userprofile\winconf\configs"
$dev_root_cert = "$dev_root\ssl\root"
$dev_host_cert = "$dev_root\ssl\host"
$wordpress_ver = "5.3"
