
$packages = @(
    "*Microsoft.3dbuilder*",
    "*AdobeSystemsIncorporated.AdobePhotoshopExpress*",
    "*Microsoft.WindowsAlarms*",
    "*Microsoft.Asphalt8Airborne*",
    "*microsoft.windowscommunicationsapps*",
    "*Microsoft.WindowsCamera*",
    "*king.com.CandyCrushSodaSaga*",
    "*Microsoft.DrawboardPDF*",
    "*Facebook*",
    "*Microsoft.OneDriveSync*"
    "*BethesdaSoftworks.FalloutShelter*",
    "*FarmVille2CountryEscape*",
    "*Microsoft.WindowsFeedbackHub*",
    "*Microsoft.GetHelp*",
    "*Microsoft.Getstarted*",
    "*Microsoft.ZuneMusic*",
    "*Microsoft.WindowsMaps*",
    "*Microsoft.Messaging*",
    "*Microsoft.Wallet*",
    "*Microsoft.MicrosoftSolitaireCollection*",
    "*ConnectivityStore*",
    "*MinecraftUWP*",
    "*Microsoft.OneConnect*",
    "*Microsoft.BingFinance*",
    "*Microsoft.ZuneVideo*",
    "*Microsoft.BingNews*",
    "*Microsoft.MicrosoftOfficeHub*",
    "*Netflix*",
    "*OneNote*",
    "*Microsoft.MSPaint*",
    "*PandoraMediaInc*",
    "*Microsoft.People*",
    "*CommsPhone*",
    "*windowsphone*",
    "*Microsoft.Print3D*",
    "*flaregamesGmbH.RoyalRevolt2*",
    "*WindowsScan*",
    "*MixedReality*",
    "*AutodeskSketchBook*",
    "*Microsoft.SkypeApp*",
    "*bingsports*",
    "*YourPhone*",
    "*Office.Sway*",
    "*MicrosoftStickyNotes*",
    "*Microsoft.Getstarted*",
    "*Twitter*",
    "*ScreenSketch*",
    "*Microsoft3DViewer*",
    "*Microsoft.WindowsSoundRecorder*",
    "*Microsoft.BingWeather*"
)

foreach ($package in $packages) {
    Get-AppxPackage $package | Remove-AppxPackage
}
