[Variables]
update.Spd=60

; Font Variables
FontName=GeoSansLight
FontName2=GeoSansLight
u-Degree=[\x00B0]

; Color Variables
FontColor=255,255,255,200
FontColor2=225,188,89
FontHeight1=100
FontHeight2=10

; Drive Variables
Drive1=C:
Drive2=
Drive3=

; Network Variables
Interface=Best

; It is IMPORTANT that these be set for YOUR network's maximum supported download and upload speeds.
; The long and the short of it is that you need to go to http://speedtest.net, run the test,
; and plug in the Download and Upload megabits per second numbers it provides in the variables below.
; See the thread at http://rainmeter.net/forum/viewtopic.php?f=15&t=16402 for details.
MaxDownloadMb=90.00
MaxUploadMb=11.00