[gui]
# Should the LaunchBox be always on top of other windows when displayed?
# * Type: Boolean
# * Default: no
always_on_top = yes
theme = JumboLayout
hide_on_focus_lost = immediate
geometry = active_monitor
retain_last_search = yes
escape_always_closes = yes

[app]
launch_at_startup = no
hotkey_run = win+d
